/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  images?: Array<{
    title?: string;
    category?: "products" | "community" | "events" | "facility" | "other";
    imageUrl?: string;
    aspectRatio?: "auto" | "tall" | "wide";
    _type: "galleryImage";
    _key: string;
  }>;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  ar?: string;
  hi?: string;
  fr?: string;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  ar?: string;
  hi?: string;
  fr?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentBanner = {
  _type: "contentBanner";
  eyebrow?: string;
  title?: string;
  highlight?: string;
  description?: string;
  features?: Array<string>;
  stats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  layout?: "bottom-image" | "right-image" | "left-image" | "background-image" | "text-only";
  imageUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bgOverlay?: "none" | "black-10" | "black-20" | "black-40" | "white-10";
  theme?: "light" | "dark";
};

export type Quote = {
  _id: string;
  _type: "quote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  author?: string;
  linkText?: string;
  linkUrl?: string;
};

export type Value = {
  _id: string;
  _type: "value";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: string;
  order?: number;
};

export type Timeline = {
  _id: string;
  _type: "timeline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: string;
  role?: string;
  location?: string;
  quote?: string;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
  bio?: string;
  order?: number;
};

export type SustainabilityPillar = {
  _id: string;
  _type: "sustainabilityPillar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  detail?: string;
  order?: number;
};

export type ProcessStep = {
  _id: string;
  _type: "processStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  detail?: string;
  icon?: "farm" | "shelling" | "sorting" | "quality" | "packing" | "shipping";
  order?: number;
};

export type DistributionRegion = {
  _id: string;
  _type: "distributionRegion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  lat?: number;
  lng?: number;
  radius?: number;
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  label?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
  order?: number;
};

export type Capability = {
  _id: string;
  _type: "capability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  metric?: string;
  icon?: string;
  order?: number;
};

export type TestimonialsSection = {
  _id: string;
  _type: "testimonialsSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  droneSection?: {
    eyebrow?: string;
    title?: string;
    placeholderText?: string;
    videoUrl?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    videos?: Array<{
      title?: string;
      description?: string;
      videoUrl?: string;
      thumbnail?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _key: string;
    }>;
    highlights?: Array<string>;
    note?: string;
  };
  backgroundImageUrl?: string;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  walkthrough?: {
    subtitle?: string;
    title?: string;
    description?: string;
    buttonText?: string;
  };
  pricing?: {
    subtitle?: string;
    title?: string;
    description?: string;
    buttonText?: string;
    emailPlaceholder?: string;
  };
  backgroundImageUrl?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type HeroSlide = {
  _id: string;
  _type: "heroSlide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline?: string;
  badge?: string;
  paragraphs?: Array<string>;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  posterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  posterImageUrl?: string;
  primaryCta?: {
    label?: string;
    target?: string;
  };
  secondaryCta?: {
    label?: string;
    target?: string;
  };
  stats?: Array<{
    value?: string;
    label?: string;
    detail?: string;
    _key: string;
  }>;
  order?: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImageUrl?: string;
  brandCopy?: string;
  productSKUs?: Array<string>;
  distributionContacts?: Array<{
    name?: string;
    email?: string;
    phone?: string;
    _key: string;
  }>;
  specSheetPDF?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  order?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
  category?:
    | "almonds"
    | "cashews"
    | "walnuts"
    | "raisins"
    | "pistachio"
    | "cardamom"
    | "coconut"
    | "dried-fig";
  description?: LocaleText;
  heroHeading?: LocaleString;
  introParagraphs?: Array<
    {
      _key: string;
    } & LocaleText
  >;
  listSections?: Array<{
    title?: LocaleString;
    items?: Array<
      {
        _key: string;
      } & LocaleString
    >;
    _key: string;
  }>;
  ctaLine?: LocaleString;
  almondVarieties?: Array<{
    name?: string;
    imageUrl?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImageUrl?: string;
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imageUrl?: string;
    alt?: string;
    _key: string;
  }>;
  microVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  specSheetPDF?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CatalogueSettings = {
  _id: string;
  _type: "catalogueSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  contentType?: "pdf" | "images";
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  pdfDownloadUrl?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  version?: string;
  lastUpdated?: string;
  isActive?: boolean;
  showThumbnails?: boolean;
  showPageNumbers?: boolean;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quickLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  certificationBadges?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  socialLinks?: {
    facebook?: string;
    twitter?: string;
    linkedin?: string;
    instagram?: string;
  };
  copyrightText?: string;
  privacyNote?: string;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  navLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  tradeButtonText?: string;
  whatsappText?: string;
  logoAlt?: string;
  homeAriaLabel?: string;
  navAriaLabel?: string;
  menuAriaLabel?: string;
  closeMenuAriaLabel?: string;
  productsLabel?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  common?: {
    viewSpecs?: string;
    addToEnquiry?: string;
    readMore?: string;
  };
  navigation?: {
    home?: string;
    about?: string;
    products?: string;
    contact?: string;
    catalogue?: string;
    productsLabel?: string;
    homeUrl?: string;
    aboutUrl?: string;
    productsUrl?: string;
    contactUrl?: string;
    catalogueUrl?: string;
  };
  footer?: {
    companyTitle?: string;
    companyDescription?: string;
    quickLinksTitle?: string;
    productsTitle?: string;
    certificationsTitle?: string;
    isoLabel?: string;
    fssaiLabel?: string;
    copyrightText?: string;
    servingText?: string;
    privacyPolicyText?: string;
    privacyNote?: string;
  };
  organization?: {
    name?: string;
    url?: string;
    logoUrl?: string;
    description?: string;
    address?: {
      streetAddress?: string;
      addressLocality?: string;
      addressRegion?: string;
      postalCode?: string;
      addressCountry?: string;
    };
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    tagline?: string;
    contactPoint?: {
      telephone?: string;
      contactType?: string;
      areaServed?: string;
      availableLanguage?: Array<string>;
    };
  };
  forms?: {
    nameLabel?: string;
    emailLabel?: string;
    phoneLabel?: string;
    messageLabel?: string;
    companyLabel?: string;
    roleLabel?: string;
    countryLabel?: string;
    productInterestLabel?: string;
    quantityLabel?: string;
    tradeQuantityPlaceholder?: string;
    submitButton?: string;
    submittingButton?: string;
    successMessage?: string;
    errorMessage?: string;
    requiredIndicator?: string;
    honeypotTabIndex?: number;
    generalEnquiryEndpoint?: string;
    tradeEnquiryEndpoint?: string;
    sampleRequestMessage?: string;
    enquiryListIntro?: string;
    populateEventName?: string;
    defaultTab?: string;
    tabValueGeneral?: string;
    tabValueTrade?: string;
  };
  enquiry?: {
    gradeLabel?: string;
    notesLabel?: string;
    packFormatLabel?: string;
    quantityLabel?: string;
    moqLabel?: string;
    emptyStateText?: string;
    pdfError?: string;
    emptyEnquiryError?: string;
    openBuilderAria?: string;
    gradePlaceholder?: string;
    packFormatPlaceholder?: string;
    quantityPlaceholder?: string;
    notesPlaceholder?: string;
    saveLabel?: string;
    cancelLabel?: string;
    editLabel?: string;
    removeAriaLabel?: string;
    spiralQuoteSection?: {
      buttonText?: string;
    };
    floatingBar?: {
      item?: string;
      items?: string;
      inYourEnquiry?: string;
      readyToSubmit?: string;
      viewEnquiry?: string;
      submitEnquiry?: string;
    };
    panel?: {
      title?: string;
      emptyState?: string;
      emptyStateSub?: string;
      exportPdf?: string;
      submitEnquiry?: string;
      clearAll?: string;
      confirmClear?: string;
      closePanelAria?: string;
    };
    builder?: {
      buttonLabel?: string;
    };
  };
  accessibility?: {
    skipLinkText?: string;
    skipLinkTarget?: string;
    heroSectionAria?: string;
    prevSlideAria?: string;
    nextSlideAria?: string;
    goToSlideAria?: string;
    closePanelAria?: string;
    closeModalAria?: string;
    themeToggleAria?: string;
    socialFacebookAria?: string;
    socialTwitterAria?: string;
    socialLinkedinAria?: string;
    socialInstagramAria?: string;
  };
  productCard?: {
    placeholderText?: string;
    specificationsTitle?: string;
    varietyLabel?: string;
    applicationsLabel?: string;
    packLabel?: string;
    moqLabel?: string;
  };
  distribution?: {
    heading?: string;
  };
  contact?: {
    officeLabel?: string;
    phoneLabel?: string;
    emailLabel?: string;
  };
  error?: {
    notFoundCode?: string;
    notFoundTitle?: string;
    notFoundText?: string;
    backHomeButton?: string;
    genericErrorTitle?: string;
    genericErrorText?: string;
    tryAgainButton?: string;
  };
  productModal?: {
    closeAria?: string;
    placeholder?: string;
    addToEnquiry?: string;
    requestSample?: string;
  };
  productDetail?: {
    addToEnquiry?: string;
    requestSample?: string;
    backToProducts?: string;
    heroPlaceholder?: string;
    programSuffix?: string;
  };
  productList?: {
    selectLabel?: string;
    varietyLabel?: string;
    packagingLabel?: string;
    quantityLabel?: string;
  };
  seo?: {
    siteUrl?: string;
    htmlLang?: string;
    metaTitle?: string;
    metaTitleSuffix?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    ogType?: string;
    twitterCardType?: string;
    robots?: {
      userAgent?: string;
      allowPath?: string;
      disallowPath?: string;
      sitemapPath?: string;
    };
    sitemap?: {
      staticPages?: Array<{
        path?: string;
        changeFrequency?: string;
        priority?: number;
        _key: string;
      }>;
      productDefaults?: {
        changeFrequency?: string;
        priority?: number;
      };
    };
  };
  apiConfig?: {
    rateLimitMaxRequests?: number;
    rateLimitWindowMs?: number;
    fallbackEmail?: string;
    enquiryTypeGeneral?: string;
    enquiryTypeTrade?: string;
    enquiryStatusNew?: string;
    listSeparator?: string;
    breadcrumbSeparator?: string;
    enquiryIdPrefix?: string;
    httpMethodPost?: string;
    contentTypeHeader?: string;
    contentTypeJson?: string;
    unknownIpLabel?: string;
  };
  apiMessages?: {
    rateLimitError?: string;
    validationError?: string;
    serverError?: string;
    enquirySuccess?: string;
    pdfGenerationError?: string;
    pdfGenerationSuccess?: string;
  };
  validation?: {
    nameMinLength?: number;
    nameMinError?: string;
    emailInvalidError?: string;
    messageMinLength?: number;
    messageMinError?: string;
    companyMinLength?: number;
    companyRequiredError?: string;
    phoneMinLength?: number;
    phoneRequiredError?: string;
    countryMinLength?: number;
    countryRequiredError?: string;
    honeypotMaxLength?: number;
  };
  routing?: {
    queryParamType?: string;
    queryParamProduct?: string;
    queryParamAction?: string;
    actionSample?: string;
    scrollTargetContact?: string;
    productsHash?: string;
    productsSectionId?: string;
    aboutSectionId?: string;
    capabilitiesSectionId?: string;
    ctaSectionId?: string;
    heroSectionId?: string;
    processSectionId?: string;
    sustainabilitySectionId?: string;
    trustSectionId?: string;
    testimonialsSectionId?: string;
  };
  analytics?: {
    eventAddToEnquiry?: string;
    eventAddToEnquiryGA?: string;
    eventSampleRequest?: string;
    eventFormSubmission?: string;
    locationProductPage?: string;
    locationModal?: string;
    formTypeGeneral?: string;
    formTypeTrade?: string;
    paramFormType?: string;
  };
  emailTemplates?: {
    fromName?: string;
    fromEmail?: string;
    generalSubject?: string;
    tradeSubject?: string;
    newGeneralEnquiryTitle?: string;
    newTradeEnquiryTitle?: string;
    nameLabel?: string;
    emailLabel?: string;
    phoneLabel?: string;
    messageLabel?: string;
    companyLabel?: string;
    roleLabel?: string;
    countryLabel?: string;
    productsLabel?: string;
    quantityLabel?: string;
    naText?: string;
    noneText?: string;
  };
  pdfTemplate?: {
    companyName?: string;
    title?: string;
    dateLabel?: string;
    referenceLabel?: string;
    referencePrefix?: string;
    contactDetailsLabel?: string;
    nameLabel?: string;
    companyLabel?: string;
    emailLabel?: string;
    phoneLabel?: string;
    indexLabel?: string;
    naText?: string;
    emptyFieldText?: string;
    filenamePrefix?: string;
    footerText1?: string;
    footerText2?: string;
    tableHeaders?: {
      product?: string;
      grade?: string;
      packFormat?: string;
      quantity?: string;
      moq?: string;
      notes?: string;
    };
    styling?: {
      fontFamily?: string;
      fontStyleNormal?: string;
      fontStyleBold?: string;
      tableTheme?: string;
      headerFontSize?: number;
      subtitleFontSize?: number;
      bodyFontSize?: number;
      footerFontSize?: number;
      tableFontSize?: number;
      tableCellPadding?: number;
      colors?: {
        deepBrown?: string;
        gray?: string;
        black?: string;
        darkGray?: string;
        gold?: string;
        white?: string;
        lightGray?: string;
      };
      columnWidths?: {
        index?: number;
        product?: number;
        grade?: number;
        packFormat?: number;
        quantity?: number;
        moq?: number;
        notes?: number;
      };
    };
  };
  whatsapp?: {
    phoneNumber?: string;
    messageTemplate?: string;
    buttonLabel?: string;
  };
  heroConfig?: {
    autoPlayInterval?: number;
    slideNumberPadding?: string;
  };
  themeToggle?: {
    toggleAria?: string;
    title?: string;
    modernLabel?: string;
    feminineLabel?: string;
  };
};

export type PrivacyPolicy = {
  _id: string;
  _type: "privacyPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  lastUpdated?: string;
  content?: Array<{
    heading?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type ProductsPage = {
  _id: string;
  _type: "productsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  description?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title?: string;
  description?: string;
  generalEnquiryLabel?: string;
  tradeEnquiryLabel?: string;
  contactDetailsTitle?: string;
  businessHoursTitle?: string;
  footerNote?: string;
  contactDetails?: {
    address?: string;
    phone?: Array<string>;
    email?: string;
  };
  businessHours?: {
    weekdays?: string;
    sunday?: string;
  };
};

export type Community = {
  _id: string;
  _type: "community";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  posterSliderSection?: {
    enabled?: boolean;
    autoPlayInterval?: number;
    posters?: Array<
      {
        _key: string;
      } & ContentBanner
    >;
  };
  header?: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
  };
  corePhilosophy?: {
    paragraph?: string;
    highlight?: string;
  };
  educationSection?: {
    icon?: string;
    title?: string;
    paragraphs?: Array<string>;
    quote?: string;
    images?: Array<string>;
  };
  womenEmpowerment?: {
    icon?: string;
    title?: string;
    paragraphs?: Array<string>;
    imageUrl?: string;
  };
  childcareSection?: {
    icon?: string;
    title?: string;
    paragraphs?: Array<string>;
    highlight?: string;
    imageUrl?: string;
  };
  industryCollaboration?: {
    icon?: string;
    title?: string;
    paragraphs?: Array<string>;
    imageUrl?: string;
  };
  environmentalSection?: {
    icon?: string;
    title?: string;
    introText?: string;
    initiatives?: Array<{
      icon?: string;
      text?: string;
      _key: string;
    }>;
    imageUrl?: string;
  };
  employeeStories?: {
    eyebrow?: string;
    title?: string;
    placeholderText?: string;
    videos?: Array<{
      title?: string;
      description?: string;
      videoUrl?: string;
      thumbnail?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _key: string;
    }>;
    highlights?: Array<string>;
    note?: string;
  };
  tradeEventsSection?: {
    title?: string;
    subtitle?: string;
  };
  tradeEvents?: Array<{
    name?: string;
    date?: string;
    location?: string;
    description?: string;
    imageUrl?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  closingMessage?: {
    title?: string;
    paragraphs?: Array<string>;
    finalHighlight?: string;
  };
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  posterSliderSection?: {
    enabled?: boolean;
    autoPlayInterval?: number;
    posters?: Array<
      {
        _key: string;
      } & ContentBanner
    >;
  };
  header?: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
  };
  openingStory?: {
    title?: string;
    highlight?: string;
    paragraphs?: Array<string>;
  };
  anjeerStory?: {
    title?: string;
    paragraphs?: Array<string>;
  };
  birthSection?: {
    title?: string;
    paragraphs?: Array<string>;
    boxTitle?: string;
    boxText?: string;
  };
  growingSection?: {
    title?: string;
    paragraphs?: Array<string>;
  };
  philosophySection?: {
    title?: string;
    highlight?: string;
    paragraphs?: Array<string>;
  };
  timelineSummaryCards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  ourStory?: {
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  whoWeAre?: {
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    stats?: Array<{
      value?: string;
      label?: string;
      _key: string;
    }>;
  };
  mission?: {
    title?: string;
    description?: string;
  };
  vision?: {
    title?: string;
    description?: string;
  };
  commitment?: {
    title?: string;
    description?: string;
  };
  brandsSection?: {
    title?: string;
    partners?: {
      title?: string;
      names?: Array<string>;
      description?: string;
      imageUrl?: string;
    };
    retail?: {
      title?: string;
      name?: string;
      description?: string;
      imageUrl?: string;
    };
  };
  productRangeSection?: {
    title?: string;
    products?: Array<string>;
    description?: string;
  };
  teamSection?: {
    eyebrow?: string;
    title?: string;
  };
  journeySection?: {
    eyebrow?: string;
    title?: string;
  };
  distributionRegions?: Array<{
    name?: string;
    description?: string;
    lat?: number;
    lng?: number;
    radius?: number;
    _key: string;
  }>;
};

export type TimelineReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "timeline";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroStats?: Array<{
    value?: string;
    label?: string;
    detail?: string;
    _key: string;
  }>;
  capabilitiesSection?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    certificationsTitle?: string;
    certificationsDescription?: string;
    backgroundImageUrl?: string;
  };
  processSection?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    backgroundImageUrl?: string;
  };
  sustainabilitySection?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    infographicImageUrl?: string;
    backgroundImageUrl?: string;
  };
  featuredBanner?: {
    imageUrl?: string;
    title?: string;
    subtitle?: string;
  };
  posterBannerSection?: {
    imageUrl?: string;
    alt?: string;
    title?: string;
  };
  droneDiaries?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    backgroundImageUrl?: string;
    videos?: Array<{
      title?: string;
      description?: string;
      videoUrl?: string;
      thumbnailUrl?: string;
      _key: string;
    }>;
  };
  trustSection?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    partnerSegments?: Array<string>;
    backgroundImageUrl?: string;
  };
  productShowcaseSection?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    backgroundImageUrl?: string;
  };
  spiralQuoteSection?: {
    buttonText?: string;
    backgroundImageUrl?: string;
  };
  videoGallery?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    videos?: Array<{
      title?: string;
      description?: string;
      videoUrl?: string;
      _key: string;
    }>;
  };
  aboutSection?: {
    whoWeAre?: {
      eyebrow?: string;
      title?: string;
      description?: string;
      stats?: Array<{
        value?: string;
        label?: string;
        _key: string;
      }>;
    };
    mission?: {
      title?: string;
      description?: string;
    };
    vision?: {
      eyebrow?: string;
      title?: string;
      description?: string;
    };
    commitment?: {
      title?: string;
      description?: string;
    };
    timeline?: {
      eyebrow?: string;
      title?: string;
      entries?: Array<
        {
          _key: string;
        } & TimelineReference
      >;
    };
    distribution?: {
      title?: string;
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | GalleryPage
  | LocaleText
  | LocaleString
  | SanityImageAssetReference
  | ContentBanner
  | Quote
  | Value
  | Timeline
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | TeamMember
  | SustainabilityPillar
  | ProcessStep
  | DistributionRegion
  | Certificate
  | Capability
  | TestimonialsSection
  | Cta
  | SanityFileAssetReference
  | HeroSlide
  | Brand
  | Product
  | Slug
  | CatalogueSettings
  | Footer
  | Header
  | SiteSettings
  | PrivacyPolicy
  | ProductsPage
  | ContactPage
  | Community
  | About
  | TimelineReference
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: app/sitemap.ts
// Variable: sitemapProductsQuery
// Query: *[_type == "product"] {     "slug": slug.current,     _updatedAt   }
export type SitemapProductsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "product"] { \n    "slug": slug.current, \n    _updatedAt \n  }\n': SitemapProductsQueryResult;
  }
}
