import { defineType, defineField } from "sanity";

export default defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "general", title: "General" },
    { name: "business", title: "Business Info" },
    { name: "labels", title: "UI Labels" },
    { name: "pages", title: "Page Settings" },
    { name: "seo", title: "SEO & Metadata" },
    { name: "api", title: "API & System" },
    { name: "pdf", title: "PDF Template" },
  ],
  fields: [
    // =========================================================================
    // GENERAL SETTINGS
    // =========================================================================
    defineField({
      name: "common",
      title: "Common UI Buttons",
      type: "object",
      group: "general",
      fields: [
        { name: "viewSpecs", type: "string", title: "View Specs Button" },
        { name: "addToEnquiry", type: "string", title: "Add to Enquiry Button" },
        { name: "readMore", type: "string", title: "Read More Button" },
      ],
    }),
    defineField({
      name: "navigation",
      title: "Main Navigation",
      type: "object",
      group: "general",
      fields: [
        { name: "home", type: "string", title: "Home Label" },
        { name: "about", type: "string", title: "About Label" },
        { name: "products", type: "string", title: "Products Label" },
        { name: "contact", type: "string", title: "Contact Label" },
        { name: "catalogue", type: "string", title: "Catalogue Label" },
        { name: "productsLabel", type: "string", title: "Products Dropdown Label" },
        { name: "homeUrl", type: "string", title: "Home URL" },
        { name: "aboutUrl", type: "string", title: "About URL" },
        { name: "productsUrl", type: "string", title: "Products URL" },
        { name: "contactUrl", type: "string", title: "Contact URL" },
        { name: "catalogueUrl", type: "string", title: "Catalogue URL" },
      ],
    }),
    defineField({
      name: "footer",
      title: "Footer Content",
      type: "object",
      group: "general",
      fields: [
        { name: "companyTitle", type: "string", title: "Company Title" },
        { name: "companyDescription", type: "text", title: "Company Description", rows: 2 },
        { name: "quickLinksTitle", type: "string", title: "Quick Links Title" },
        { name: "productsTitle", type: "string", title: "Products Title" },
        { name: "certificationsTitle", type: "string", title: "Certifications Title" },
        { name: "isoLabel", type: "string", title: "ISO Label" },
        { name: "fssaiLabel", type: "string", title: "FSSAI Label" },
        { name: "copyrightText", type: "string", title: "Copyright Text" },
        { name: "servingText", type: "string", title: "Serving Region Text" },
        { name: "privacyPolicyText", type: "string", title: "Privacy Policy Link Text" },
        { name: "privacyNote", type: "string", title: "Privacy Note (Small)" },
      ],
    }),

    // =========================================================================
    // BUSINESS INFO
    // =========================================================================
    defineField({
      name: "organization",
      title: "Organization Schema",
      type: "object",
      group: "business",
      fields: [
        { name: "name", type: "string", title: "Organization Name" },
        { name: "url", type: "url", title: "Website URL" },
        { name: "logoUrl", type: "url", title: "Logo URL (Public)" },
        { name: "description", type: "text", title: "Description" },
        {
          name: "address",
          type: "object",
          title: "Address",
          fields: [
            { name: "streetAddress", type: "string", title: "Street" },
            { name: "addressLocality", type: "string", title: "City" },
            { name: "addressRegion", type: "string", title: "State" },
            { name: "postalCode", type: "string", title: "Postal Code" },
            { name: "addressCountry", type: "string", title: "Country Code (IN)" },
          ],
        },
        { name: "logo", type: "image", title: "Logo Image", options: { hotspot: true } },
        { name: "tagline", type: "string", title: "Tagline" },
        {
          name: "contactPoint",
          type: "object",
          title: "Contact Point",
          fields: [
            { name: "telephone", type: "string", title: "Phone" },
            { name: "contactType", type: "string", title: "Type (e.g., sales)" },
            { name: "areaServed", type: "string", title: "Area Served" },
            {
              name: "availableLanguage",
              type: "array",
              of: [{ type: "string" }],
              title: "Languages",
            },
          ],
        },
      ],
    }),

    // =========================================================================
    // UI LABELS
    // =========================================================================
    defineField({
      name: "forms",
      title: "Form Labels",
      type: "object",
      group: "labels",
      fields: [
        { name: "nameLabel", type: "string", title: "Name" },
        { name: "emailLabel", type: "string", title: "Email" },
        { name: "phoneLabel", type: "string", title: "Phone" },
        { name: "messageLabel", type: "string", title: "Message" },
        { name: "companyLabel", type: "string", title: "Company" },
        { name: "roleLabel", type: "string", title: "Role" },
        { name: "countryLabel", type: "string", title: "Country" },
        { name: "productInterestLabel", type: "string", title: "Product Interest" },
        { name: "quantityLabel", type: "string", title: "Quantity" },
        { name: "tradeQuantityPlaceholder", type: "string", title: "Trade Qty Placeholder" },
        { name: "submitButton", type: "string", title: "Submit Button" },
        { name: "submittingButton", type: "string", title: "Submitting Button" },
        { name: "successMessage", type: "string", title: "Success Message" },
        { name: "errorMessage", type: "string", title: "Error Message" },
        { name: "requiredIndicator", type: "string", title: "Required *" },
        { name: "honeypotTabIndex", type: "number", title: "Honeypot Index" },
        { name: "generalEnquiryEndpoint", type: "string", title: "General Endpoint" },
        { name: "tradeEnquiryEndpoint", type: "string", title: "Trade Endpoint" },
        { name: "sampleRequestMessage", type: "string", title: "Sample Message Template" },
        { name: "enquiryListIntro", type: "string", title: "Enquiry List Intro" },
        { name: "populateEventName", type: "string", title: "Populate Event Name" },
        { name: "defaultTab", type: "string", title: "Default Tab" },
        { name: "tabValueGeneral", type: "string", title: "General Tab Value" },
        { name: "tabValueTrade", type: "string", title: "Trade Tab Value" },
      ],
    }),
    defineField({
      name: "enquiry",
      title: "Enquiry UI Settings",
      type: "object",
      group: "labels",
      fields: [
        // Fields
        { name: "gradeLabel", type: "string", title: "Grade Label" },
        { name: "notesLabel", type: "string", title: "Notes Label" },
        { name: "packFormatLabel", type: "string", title: "Pack Label" },
        { name: "quantityLabel", type: "string", title: "Qty Label" },
        { name: "moqLabel", type: "string", title: "MOQ Label" },
        // States
        { name: "emptyStateText", type: "string", title: "Empty State" },
        { name: "pdfError", type: "string", title: "PDF Error" },
        { name: "emptyEnquiryError", type: "string", title: "Empty Enquiry Error" },
        { name: "openBuilderAria", type: "string", title: "Open Aria" },
        // Placeholders
        { name: "gradePlaceholder", type: "string", title: "Grade Placeholder" },
        { name: "packFormatPlaceholder", type: "string", title: "Pack Placeholder" },
        { name: "quantityPlaceholder", type: "string", title: "Qty Placeholder" },
        { name: "notesPlaceholder", type: "string", title: "Notes Placeholder" },
        // Actions
        { name: "saveLabel", type: "string", title: "Save" },
        { name: "cancelLabel", type: "string", title: "Cancel" },
        { name: "editLabel", type: "string", title: "Edit" },
        { name: "removeAriaLabel", type: "string", title: "Remove Aria" },
        // Sections
        defineField({
          name: "spiralQuoteSection",
          title: "Spiral Quote Button",
          type: "object",
          fields: [{ name: "buttonText", type: "string", title: "Button Text" }],
        }),
        defineField({
          name: "floatingBar",
          title: "Floating Bar",
          type: "object",
          fields: [
            { name: "item", type: "string", title: "Item (Singular)" },
            { name: "items", type: "string", title: "Items (Plural)" },
            { name: "inYourEnquiry", type: "string", title: "In Your Enquiry" },
            { name: "readyToSubmit", type: "string", title: "Ready To Submit Text" },
            { name: "viewEnquiry", type: "string", title: "View Button" },
            { name: "submitEnquiry", type: "string", title: "Submit Button" },
          ],
        }),
        defineField({
          name: "panel",
          title: "Side Panel",
          type: "object",
          fields: [
            { name: "title", type: "string", title: "Title" },
            { name: "emptyState", type: "string", title: "Empty Text" },
            { name: "emptyStateSub", type: "string", title: "Empty Subtext" },
            { name: "exportPdf", type: "string", title: "Export PDF Button" },
            { name: "submitEnquiry", type: "string", title: "Submit Button" },
            { name: "clearAll", type: "string", title: "Clear Button" },
            { name: "confirmClear", type: "string", title: "Confirm Clear msg" },
            { name: "closePanelAria", type: "string", title: "Close Aria" },
          ],
        }),
        defineField({
          name: "builder",
          title: "Builder Modal",
          type: "object",
          fields: [{ name: "buttonLabel", type: "string", title: "Add Button Label" }],
        }),
      ],
    }),
    defineField({
      name: "accessibility",
      title: "Accessibility Strings",
      type: "object",
      group: "labels",
      fields: [
        { name: "skipLinkText", type: "string", title: "Skip Link Text" },
        { name: "skipLinkTarget", type: "string", title: "Skip Link Target ID" },
        { name: "heroSectionAria", type: "string", title: "Hero Section Aria" },
        { name: "prevSlideAria", type: "string", title: "Prev Slide Aria" },
        { name: "nextSlideAria", type: "string", title: "Next Slide Aria" },
        { name: "goToSlideAria", type: "string", title: "Go to Slide Aria" },
        { name: "closePanelAria", type: "string", title: "Close Panel Aria" },
        { name: "closeModalAria", type: "string", title: "Close Modal Aria" },
        { name: "themeToggleAria", type: "string", title: "Theme Toggle Aria" },
        { name: "socialFacebookAria", type: "string", title: "Facebook Aria" },
        { name: "socialTwitterAria", type: "string", title: "Twitter Aria" },
        { name: "socialLinkedinAria", type: "string", title: "LinkedIn Aria" },
        { name: "socialInstagramAria", type: "string", title: "Instagram Aria" },
      ],
    }),

    // =========================================================================
    // PAGE SETTINGS
    // =========================================================================
    defineField({
      name: "productCard",
      title: "Product Card",
      type: "object",
      group: "pages",
      fields: [
        { name: "placeholderText", type: "string", title: "Placeholder Text" },
        { name: "specificationsTitle", type: "string", title: "Specs Title" },
        { name: "varietyLabel", type: "string", title: "Variety Label" },
        { name: "applicationsLabel", type: "string", title: "Apps Label" },
        { name: "packLabel", type: "string", title: "Pack Label" },
        { name: "moqLabel", type: "string", title: "MOQ Label" },
      ],
    }),
    defineField({
      name: "distribution",
      title: "Distribution Page",
      type: "object",
      group: "pages",
      fields: [{ name: "heading", type: "string", title: "Heading" }],
    }),
    defineField({
      name: "contact",
      title: "Contact Page",
      type: "object",
      group: "pages",
      fields: [
        { name: "officeLabel", type: "string", title: "Office Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
      ],
    }),
    defineField({
      name: "error",
      title: "Error Page Labels",
      type: "object",
      group: "pages",
      fields: [
        { name: "notFoundCode", type: "string", title: "404 Code" },
        { name: "notFoundTitle", type: "string", title: "404 Title" },
        { name: "notFoundText", type: "string", title: "404 Text" },
        { name: "backHomeButton", type: "string", title: "Back Home Btn" },
        { name: "genericErrorTitle", type: "string", title: "Error Title" },
        { name: "genericErrorText", type: "string", title: "Error Text" },
        { name: "tryAgainButton", type: "string", title: "Try Again Btn" },
      ],
    }),
    // PRODUCT SUB-SETTINGS (Modal, Detail, List)
    defineField({
      name: "productModal",
      title: "Product Modal",
      type: "object",
      group: "pages",
      fields: [
        { name: "closeAria", type: "string", title: "Close Aria" },
        { name: "placeholder", type: "string", title: "Placeholder" },
        { name: "addToEnquiry", type: "string", title: "Add Button" },
        { name: "requestSample", type: "string", title: "Request Sample" },
      ],
    }),
    defineField({
      name: "productDetail",
      title: "Product Detail Page",
      type: "object",
      group: "pages",
      fields: [
        { name: "addToEnquiry", type: "string", title: "Add Button" },
        { name: "requestSample", type: "string", title: "Request Sample" },
        { name: "backToProducts", type: "string", title: "Back Link" },
        { name: "heroPlaceholder", type: "string", title: "Hero Placeholder" },
        { name: "programSuffix", type: "string", title: "Program Suffix" },
      ],
    }),
    defineField({
      name: "productList",
      title: "Product List View",
      type: "object",
      group: "pages",
      fields: [
        { name: "selectLabel", type: "string", title: "Select Checkbox" },
        { name: "varietyLabel", type: "string", title: "Variety Label" },
        { name: "packagingLabel", type: "string", title: "Pack Label" },
        { name: "quantityLabel", type: "string", title: "Qty Label" },
      ],
    }),

    // =========================================================================
    // SEO & METADATA
    // =========================================================================
    defineField({
      name: "seo",
      title: "Global SEO",
      type: "object",
      group: "seo",
      fields: [
        { name: "siteUrl", type: "url", title: "Site URL" },
        { name: "htmlLang", type: "string", title: "HTML Lang", initialValue: "en" },
        { name: "metaTitle", type: "string", title: "Meta Title" },
        { name: "metaTitleSuffix", type: "string", title: "Title Suffix" },
        { name: "metaDescription", type: "text", title: "Meta Description", rows: 3 },
        { name: "keywords", type: "array", of: [{ type: "string" }], title: "Keywords" },
        { name: "ogType", type: "string", title: "OG Type", initialValue: "website" },
        {
          name: "twitterCardType",
          type: "string",
          title: "Twitter Card",
          initialValue: "summary_large_image",
        },
        defineField({
          name: "robots",
          type: "object",
          title: "Robots.txt",
          fields: [
            { name: "userAgent", type: "string" },
            { name: "allowPath", type: "string" },
            { name: "disallowPath", type: "string" },
            { name: "sitemapPath", type: "string" },
          ],
        }),
        defineField({
          name: "sitemap",
          type: "object",
          title: "Sitemap Config",
          fields: [
            {
              name: "staticPages",
              type: "array",
              title: "Static Pages",
              of: [
                {
                  type: "object",
                  fields: [
                    { name: "path", type: "string" },
                    { name: "changeFrequency", type: "string" },
                    { name: "priority", type: "number" },
                  ],
                },
              ],
            },
            {
              name: "productDefaults",
              type: "object",
              title: "Product Page Defaults",
              fields: [
                { name: "changeFrequency", type: "string" },
                { name: "priority", type: "number" },
              ],
            },
          ],
        }),
      ],
    }),

    // =========================================================================
    // API & SYSTEM
    // =========================================================================
    defineField({
      name: "apiConfig",
      title: "API Settings",
      type: "object",
      group: "api",
      fields: [
        { name: "rateLimitMaxRequests", type: "number", title: "Rate Limit Max" },
        { name: "rateLimitWindowMs", type: "number", title: "Rate Limit Window (ms)" },
        { name: "fallbackEmail", type: "string", title: "Fallback Email" },
        // Constants used by API routes
        { name: "enquiryTypeGeneral", type: "string", title: "Type: General" },
        { name: "enquiryTypeTrade", type: "string", title: "Type: Trade" },
        { name: "enquiryStatusNew", type: "string", title: "Status: New" },
        { name: "listSeparator", type: "string", title: "List Separator" },
        { name: "breadcrumbSeparator", type: "string", title: "Breadcrumb Separator" },
        { name: "enquiryIdPrefix", type: "string", title: "Enquiry ID Prefix" },
        { name: "httpMethodPost", type: "string", title: "HTTP POST" },
        { name: "contentTypeHeader", type: "string", title: "Content-Type Header" },
        { name: "contentTypeJson", type: "string", title: "Content-Type JSON" },
        { name: "unknownIpLabel", type: "string", title: "Unknown IP Label" },
      ],
    }),
    defineField({
      name: "apiMessages",
      title: "API Messages",
      type: "object",
      group: "api",
      fields: [
        { name: "rateLimitError", type: "string", title: "Rate Limit Error" },
        { name: "validationError", type: "string", title: "Validation Error" },
        { name: "serverError", type: "string", title: "Server Error" },
        { name: "enquirySuccess", type: "string", title: "Success Message" },
        { name: "pdfGenerationError", type: "string", title: "PDF Gen Error" },
        { name: "pdfGenerationSuccess", type: "string", title: "PDF Gen Success" },
      ],
    }),
    defineField({
      name: "validation",
      title: "Validation Rules (Regex/Lengths)",
      type: "object",
      group: "api",
      fields: [
        { name: "nameMinLength", type: "number", title: "Name Min Length" },
        { name: "nameMinError", type: "string", title: "Name Error" },
        { name: "emailInvalidError", type: "string", title: "Email Error" },
        { name: "messageMinLength", type: "number", title: "Message Min Length" },
        { name: "messageMinError", type: "string", title: "Message Error" },
        { name: "companyMinLength", type: "number", title: "Company Min Length" },
        { name: "companyRequiredError", type: "string", title: "Company Error" },
        { name: "phoneMinLength", type: "number", title: "Phone Min Length" },
        { name: "phoneRequiredError", type: "string", title: "Phone Error" },
        { name: "countryMinLength", type: "number", title: "Country Min Length" },
        { name: "countryRequiredError", type: "string", title: "Country Error" },
        { name: "honeypotMaxLength", type: "number", title: "Honeypot Max Length" },
      ],
    }),
    defineField({
      name: "routing",
      title: "Routing Constants",
      type: "object",
      group: "api",
      fields: [
        { name: "queryParamType", type: "string", title: "Param: Type" },
        { name: "queryParamProduct", type: "string", title: "Param: Product" },
        { name: "queryParamAction", type: "string", title: "Param: Action" },
        { name: "actionSample", type: "string", title: "Value: Sample" },
        { name: "scrollTargetContact", type: "string", title: "Target: Contact" },
        { name: "productsHash", type: "string", title: "Hash: Products" },
        { name: "productsSectionId", type: "string", title: "ID: Products" },
        { name: "aboutSectionId", type: "string", title: "ID: About" },
        { name: "capabilitiesSectionId", type: "string", title: "ID: Capabilities" },
        { name: "ctaSectionId", type: "string", title: "ID: CTA" },
        { name: "heroSectionId", type: "string", title: "ID: Hero" },
        { name: "processSectionId", type: "string", title: "ID: Process" },
        { name: "sustainabilitySectionId", type: "string", title: "ID: Sustainability" },
        { name: "trustSectionId", type: "string", title: "ID: Trust" },
        { name: "testimonialsSectionId", type: "string", title: "ID: Testimonials" },
      ],
    }),
    defineField({
      name: "analytics",
      title: "Analytics IDs",
      type: "object",
      group: "api",
      fields: [
        { name: "eventAddToEnquiry", type: "string", title: "Event: Add" },
        { name: "eventAddToEnquiryGA", type: "string", title: "Event: Add (GA)" },
        { name: "eventSampleRequest", type: "string", title: "Event: Sample" },
        { name: "eventFormSubmission", type: "string", title: "Event: Submit" },
        { name: "locationProductPage", type: "string", title: "Loc: Product" },
        { name: "locationModal", type: "string", title: "Loc: Modal" },
        { name: "formTypeGeneral", type: "string", title: "Type: General" },
        { name: "formTypeTrade", type: "string", title: "Type: Trade" },
        { name: "paramFormType", type: "string", title: "Param: FormType" },
      ],
    }),
    defineField({
      name: "emailTemplates",
      title: "Email Templates",
      type: "object",
      group: "api",
      fields: [
        { name: "fromName", type: "string", title: "Sender Name" },
        { name: "fromEmail", type: "string", title: "Sender Email" },
        { name: "generalSubject", type: "string", title: "Subject: General" },
        { name: "tradeSubject", type: "string", title: "Subject: Trade" },
        { name: "newGeneralEnquiryTitle", type: "string", title: "Title: General" },
        { name: "newTradeEnquiryTitle", type: "string", title: "Title: Trade" },
        { name: "nameLabel", type: "string", title: "Name Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "messageLabel", type: "string", title: "Message Label" },
        { name: "companyLabel", type: "string", title: "Company Label" },
        { name: "roleLabel", type: "string", title: "Role Label" },
        { name: "countryLabel", type: "string", title: "Country Label" },
        { name: "productsLabel", type: "string", title: "Products Label" },
        { name: "quantityLabel", type: "string", title: "Qty Label" },
        { name: "naText", type: "string", title: "N/A Text" },
        { name: "noneText", type: "string", title: "None Text" },
      ],
    }),

    // =========================================================================
    // PDF TEMPLATE
    // =========================================================================
    defineField({
      name: "pdfTemplate",
      title: "PDF Styling & Logic",
      type: "object",
      group: "pdf",
      fields: [
        { name: "companyName", type: "string", title: "Company Name" },
        { name: "title", type: "string", title: "Doc Title" },
        { name: "dateLabel", type: "string", title: "Date Label" },
        { name: "referenceLabel", type: "string", title: "Ref Label" },
        { name: "referencePrefix", type: "string", title: "Ref Prefix" },
        { name: "contactDetailsLabel", type: "string", title: "Contact Label" },
        { name: "nameLabel", type: "string", title: "Name Label" },
        { name: "companyLabel", type: "string", title: "Company Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "indexLabel", type: "string", title: "Idx Label" },
        { name: "naText", type: "string", title: "N/A Text" },
        { name: "emptyFieldText", type: "string", title: "Empty Text" },
        { name: "filenamePrefix", type: "string", title: "File Prefix" },
        { name: "footerText1", type: "string", title: "Footer 1" },
        { name: "footerText2", type: "string", title: "Footer 2" },
        {
          name: "tableHeaders",
          type: "object",
          title: "Table Headers",
          fields: [
            { name: "product", type: "string" },
            { name: "grade", type: "string" },
            { name: "packFormat", type: "string" },
            { name: "quantity", type: "string" },
            { name: "moq", type: "string" },
            { name: "notes", type: "string" },
          ],
        },
        {
          name: "styling",
          type: "object",
          title: "PDF Styling",
          fields: [
            { name: "fontFamily", type: "string" },
            { name: "fontStyleNormal", type: "string" },
            { name: "fontStyleBold", type: "string" },
            { name: "tableTheme", type: "string" },
            { name: "headerFontSize", type: "number" },
            { name: "subtitleFontSize", type: "number" },
            { name: "bodyFontSize", type: "number" },
            { name: "footerFontSize", type: "number" },
            { name: "tableFontSize", type: "number" },
            { name: "tableCellPadding", type: "number" },
            {
              name: "colors",
              type: "object",
              title: "Colors",
              fields: [
                { name: "deepBrown", type: "string" },
                { name: "gray", type: "string" },
                { name: "black", type: "string" },
                { name: "darkGray", type: "string" },
                { name: "gold", type: "string" },
                { name: "white", type: "string" },
                { name: "lightGray", type: "string" },
              ],
            },
            {
              name: "columnWidths",
              type: "object",
              title: "Column Widths",
              fields: [
                { name: "index", type: "number" },
                { name: "product", type: "number" },
                { name: "grade", type: "number" },
                { name: "packFormat", type: "number" },
                { name: "quantity", type: "number" },
                { name: "moq", type: "number" },
                { name: "notes", type: "number" },
              ],
            },
          ],
        },
      ],
    }),

    // =========================================================================
    // MISC SETTINGS
    // =========================================================================
    defineField({
      name: "whatsapp",
      title: "WhatsApp",
      type: "object",
      group: "general",
      fields: [
        { name: "phoneNumber", type: "string", title: "Phone (Intl format)" },
        { name: "messageTemplate", type: "text", title: "Template" },
        { name: "buttonLabel", type: "string", title: "Button Aria" },
      ],
    }),
    defineField({
      name: "heroConfig",
      title: "Hero Slider Config",
      type: "object",
      group: "general",
      fields: [
        { name: "autoPlayInterval", type: "number", title: "Interval (ms)" },
        { name: "slideNumberPadding", type: "string", title: "Padding Char" },
      ],
    }),
    defineField({
      name: "themeToggle",
      title: "Theme Toggle Labels",
      type: "object",
      group: "general",
      fields: [
        { name: "toggleAria", type: "string" },
        { name: "title", type: "string" },
        { name: "modernLabel", type: "string" },
        { name: "feminineLabel", type: "string" },
      ],
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Global Site Settings",
        subtitle: "Configuration",
      };
    },
  },
});
